### PR TITLE
[RRR] random round robin

### PR DESCRIPTION
**Pull request by kuritka**
related to https://github.com/k8gb-io/k8gb/issues/50

there is difference between those three:
```yaml
# RRR
  strategy:
    type: roundRobin
    splitBrainThresholdSeconds: 300
    dnsTtlSeconds: 30
```

```yaml
# WRR
  strategy:
    type: roundRobin
    splitBrainThresholdSeconds: 300
    dnsTtlSeconds: 30
    weight:
      eu: 1
      us: 1
```

```yaml
# SKIP
  strategy:
    type: roundRobin
    splitBrainThresholdSeconds: 300
    dnsTtlSeconds: 30
    weight:
      eu: 1
```

The difference is that first one provides standard coreDNS `loadbalance round_robin`(RRR) while second one enables WRR. The third one is incompleted.

We cannot easily switch balancing in corefile to enable RRR and disable WRR when GSLB configuration has change.

This PR contains functionality that switches between WRR, RRR  and doing nothing (SKIP - returns list of IPs without  shuffling) .

I'm reusing CoreDNS loadbalance to perform RRR.

```shell
k8gb-coredns-5454ddd5b7-r555w coredns [INFO] plugin/wrr: [random][172.18.0.3 172.18.0.4 172.18.0.6 172.18.0.5]
k8gb-coredns-5454ddd5b7-r555w coredns [INFO] plugin/wrr: [random][172.18.0.6 172.18.0.3 172.18.0.4 172.18.0.5]
k8gb-coredns-5454ddd5b7-r555w coredns [INFO] plugin/wrr: [random][172.18.0.4 172.18.0.3 172.18.0.5 172.18.0.6]
k8gb-coredns-5454ddd5b7-r555w coredns [INFO] plugin/wrr: [1 0][us1 eu1]: [172.18.0.5 172.18.0.6 172.18.0.3 172.18.0.4]
k8gb-coredns-5454ddd5b7-r555w coredns [INFO] plugin/wrr: [0 1][eu1 us1]: [172.18.0.3 172.18.0.4 172.18.0.5 172.18.0.6]
k8gb-coredns-5454ddd5b7-r555w coredns [INFO] plugin/wrr: [1 0][us1 eu1]: [172.18.0.5 172.18.0.6 172.18.0.4 172.18.0.3]
k8gb-coredns-79458796bb-mq855 coredns [INFO] plugin/wrr: [skipping][172.18.0.5 172.18.0.6 172.18.0.3 172.18.0.4]
k8gb-coredns-79458796bb-mq855 coredns [INFO] plugin/wrr: [skipping][172.18.0.5 172.18.0.6 172.18.0.3 172.18.0.4]
k8gb-coredns-79458796bb-mq855 coredns [INFO] plugin/wrr: [skipping][172.18.0.5 172.18.0.6 172.18.0.3 172.18.0.4]
```

Signed-off-by: kuritka <kuritka@gmail.com>

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Will it still keep the default RRR in a broader k8gb context?

**Comment by kuritka** [comment]
@ytsarev , good question:

Before WRR we had such Corefile

```yaml
    cloud.example.com:5353 {
        errors
        health
        ready
        loadbalance round_robin <---
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        k8s_crd {
            filter k8gb.absa.oss/dnstype=local
            negttl 10
        }
    }
```
^^^ originally it only balanced the RRR. Nuw  we deploed modified Corefile:

```yaml
    cloud.example.com:5353 {
        errors
        health
        ready
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        k8s_crd {
            filter k8gb.absa.oss/dnstype=local
            negttl 10
            loadbalance weight  <---
        }
    }
```
`loadbalance weight` behaves as mentioned in PR description (if set correctly weight, RRR if GSLB configuration without weight settings, or SKIP - maybe we can remove SKIP and use RRR instead, so it always balance somehow, even when endpoint is corrupted.   


PS: about  SKIP. SKIP is established in situation when targets differs from labels. It usually happen during sync. It takes TTL  before change may propagate. 
```yaml
# SKIP situation
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: weight-eu-5-us-5
  labels:
    k8gb.absa.oss/dnstype: local
  annotations:
    k8gb.absa.oss/dnstype: local
spec:
  endpoints:
  - dnsName: weight-eu-5-us-5.example.org
    recordTTL: 30
    recordType: A
    labels:
      strategy: roundRobin
      weight-eu-0-5: 172.18.0.3
      weight-eu-1-5: 172.18.0.4
#      weight-us-0-5: 172.18.0.5 <--- by removing those two incocistence happens. DNS answer will
#      weight-us-1-5: 172.18.0.6  <-- have 4 records while weigh cover only two
    targets:
    - 172.18.0.5
    - 172.18.0.6
    - 172.18.0.3
    - 172.18.0.4
```

**Comment by kuritka** [comment]
PS2: 

Originally I was also thinking about adding strategy:

```json
    cloud.example.com:5353 {
        errors
        health
        ready
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        k8s_crd {
            filter k8gb.absa.oss/dnstype=local
            negttl 10
            loadbalance random  <---
        }
    }
```
But at the moment I don't see use-case for that.  But if you see, let me know please.  I can add in different PR.

**Review by ytsarev — APPROVED** [review]
Thanks a lot, let's integrate it into k8gb! 

@kuritka we need to document it though, the documentation will be extended at k8gb level, is that correct?

**Comment by kuritka** [comment]
Hi, thx for review. Would be documented, just not sure if I understand _the documentation will be extended at k8gb level_ ?

**Comment by ytsarev** [comment]
@kuritka  By k8gb level, I mean the main project documentation we have at k8gb.io. In contrast to the documentation located in this specific repository.

**Pull request merged**
