### PR TITLE
feat: Configurable geoip data file and data field path 

### PR DESCRIPTION
**Pull request by jimmidyson**
This commit adds the option to configure the geoip database file path
and the data field to use. The existing defaults are preserved by setting
default values for the new options.

This has been tested against the maxmind geolite2 database, using
`country.iso_code` and `continent.code` field paths.

### CODE REVIEW

**Review by ytsarev — APPROVED** [review]
This looks great, thanks for the contribution!

@k0da could you take another look before we merge?

**Comment by ytsarev** [comment]
Hm, looks like we also need to check terratest run

**Review by k0da — APPROVED** [review]
👍 LGTM

**Comment by ytsarev** [comment]
@jimmidyson @k0da i've reproduced the terratest failure locally and disable parallelism for the basic example test in https://github.com/k8gb-io/coredns-crd-plugin/pull/56/commits/5db8eb8fa25b5265fb681b023f5a787c1b7c94d1 
Now it looks pretty stable after multiple local invocations and in this PR ( @jimmidyson ,  I pushed the fix to your feature branch, hope you don't mind :) ) 

As everything is green, I am merging this PR

**Pull request merged**
